### ISSUE TITLE
January BeerJS

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#16]
Hey folks! Just getting back to normal after a crazy month. 

So I'm out of town on the last Wednesday of the month (1/28). If we want to stick with tradition, I'm totally cool missing this one.

The other option is to move it up a week to Wednesday 1/21. That's next Wednesday. 

Thoughts?

**Comment by ctm** [comment]
My opinion should count but epsilon, however I'd say move it to the 21st. You could probably use a beer and that will also avoid a conflict with Michael Deitcher's Ember presentation at RubiABQ which was moved from the 14th to the 28th due to laryngitis.

**Comment by orbiteleven** [comment]
Anyone else? If it's just Cliff and I interested this month I might just go bowling

**Comment by ianwcarlson** [comment]
I can't make it tomorrow.  I know that doesn't help much.

**Comment by ianwcarlson** [comment]
No BeerJS this month?

**Comment by orbiteleven** [comment]
Ugh... I'm gonna be out of town again! I'll add a new date for those available.
