### ISSUE TITLE
25 February BeerJS!

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#17]
I'll be out of town again, but I'm just one man. I'm proposing same bat-time, same bat-place: 7pm @ Red Door Brewery, 1001 Candaleria Rd NE. Reply so other folks know who's going.

**Comment by craig-davis** [comment]
I don't want to see this little group whither! I'm out tomorrow as well. But I'm bumping this to get a headcount and remind y'all about the day.

(Also, the new Marionette 2.4 is out, and it's looking pretty tidy with new collection view filters.)

**Comment by ianwcarlson** [comment]
I'm able to go if a few others respond.

**Comment by orbiteleven** [comment]
Hope y'all met and had fun!
