### ISSUE TITLE
25 March BeerJS!

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#18]
Alright folks, 3 months into 2015 and I'm finally getting in front of this. 

Same bat time, same bat channel: let's meet up at 7pm on 25 March, Red Door Brewery.

**Comment by gbass84** [comment]
It doesn't have to be this one, but can we all talk about asm.js? It's now going to be in the IE replacement for Win10, and Chrome announced it will be in the next release. I was reading on it last night and had to get drool bucket for my desk. Any Interest?

http://asmjs.org/spec/latest/

**Comment by ellotheth** [comment]
I can come this time! Is it ok that I haven't done serious JS work in a few months?

@gbass84 Are you volunteering to talk about it? ;p I'm interested, but I know really nothing about it.

**Comment by thejones** [comment]
Is this still happening?

**Comment by michaeldeitcher** [comment]
I'll be there after RubiABQ which ends at 8. I'm hoping to bring other Rubyists who are interested in driking beer and what's happening in javascript-land.

**Comment by orbiteleven** [comment]
@gbass84 No reason you can't bring it up. This is a pretty informal event--no specific speakers or subjects--so I'd say strike up a conversation about it!

@ellotheth We've got pretty strict restrictions that you must have written a JS closure or used a Promise interface within 4 hours of attending, so see what you can do ;)

@thejones I'll be there. I'm gathering that others will to!

**Comment by mark-casias** [comment]
Can't make it tonight. Have a few for me.

**Comment by ianwcarlson** [comment]
I'll be able to make it

**Comment by orbiteleven** [comment]
In the back wearing a cowboy hat






On Wednesday, Mar 25, 2015 at 18:21, Ian Carlson <notifications@github.com>, wrote:

I'll be able to make it

**Comment by joshuatomasgarcia** [comment]
I think I saw you guys there! I was there to see the music at 9pm. I'll have to join you next time!!

**Comment by orbiteleven** [comment]
Great turnout! Setting up this month's beers!
