### ISSUE TITLE
April 29 Beer.js

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#19]
April is upon us! Are folks still happy with Red Door? I am, but I'm open to mixing it up, too.

Other details are the same: 7pm, happy hour format.

**Comment by mark-casias** [comment]
I am a fan of Red Door.

**Comment by orbiteleven** [comment]
Hey! Look at that! It's already April 28th, which means that yesterday was April 27th! It ALSO means that tomorrow is April 28th. Hope to see a bunch of you out at Red Door Brewery, 1001 Candaleria NE at 7pm!

**Comment by teampoop** [comment]
Wait.. tomorrow's gonna be the 28th again?

**Comment by orbiteleven** [comment]
I have no idea what you're talking about ;)

**Comment by samatjain** [comment]
How long do you guys hang out? I'll be late tomorrow.

Does Red Door allow dogs inside? Could we get seating that is dog friendly? 🐶

**Comment by mark-casias** [comment]
Red Door is pet friendly and I'll probably have my dog with me as well.

**Comment by ctm** [comment]
Dang, got called on a SAR mission in the Gila. See y'all next time, I hope.

**Comment by orbiteleven** [comment]
Cowboy hat, watching hockey by garage door

**Comment by samatjain** [comment]
Great meet up!

Just wondering… was there an actual happy hour in the evening? I miss happy hour prices. =/

**Comment by orbiteleven** [comment]
Fun times last month. This month's BeerJS is up.

@samatjain Not sure... we can play around with times to hook into some of Happy Hour (if they have one). 7pm was just what worked for me when first starting the group. Check out #20 and propose earlier if you think you can get folks out!
