### ISSUE TITLE
May BeerJS!

### ISSUE THREAD

**Issue by ctm** [beerjs/abq#20]
Is it going on? I'm increasingly interested in ember, but it seems like I decreasingly have free time to explore it. I still make time to drink beer though.

**Comment by orbiteleven** [comment]
Totally! I *might* not be able to make this one, but please spread the word! Red Door Brewery, May 24th, 7pm.

**Comment by samatjain** [comment]
I'm OOT. 😐 Any chance of Thurs May 28?

**Comment by samatjain** [comment]
@ctm I actually have a beer-related Ember project I wanted to start…

**Comment by orbiteleven** [comment]
I'm open to Thursday... @ctm ? Others?

**Comment by brianarn** [comment]
May 24th is a Sunday, is this moving to Sundays now? Would have guessed that it'd be on the 27th, but it's been so long since I could make it, I have no idea.

Still out this go-round too, no matter when it is, I'll be at jsconf. :D

**Comment by orbiteleven** [comment]
D'oh! Yeah, I think we're looking at Wednesday, 5/27 or Thursday, 5/28... unless @ctm was purposely trying to move this to Sunday ;)

**Comment by mark-casias** [comment]
Thursday May 28th works better for me..

**Comment by ctm** [comment]
I was looking at June and not realizing it, so no I wasn't trying to shift to Sunday. I'm open to either May 27th or 28th. Were all else equal, I'd prefer Wednesday, May 27th, because I already reserve Thursday nights to drink beer and shoot pool. OTOH, the early consensus is favoring the 28th, so I'm happy to support that.

Tonight, however, I'm going to [OpenHack](http://openhack.github.io/albuquerque/).

**Comment by ctm** [comment]
Looks like "[Yelptropolis](http://www.yelp.com/events/albuquerque-yelptropolis-2015)" is May 28th, too. I don't if that affects anyone. I don't know that I own or want any "Yelpy futuristic threads".

**Comment by orbiteleven** [comment]
Oh crap... that totally affects things for me as I'm RSVP'd for Yelptropolis. Again, I'm one person so pick a date that works for the most people.

**Comment by ctm** [comment]
Wednesday? Thursday?

**Comment by orbiteleven** [comment]
Sadly I can't make either of these, though I might skip Yelptropolis for Thursday if there's a few folks coming out. I think the consensus was Thursday.

Nothing like planning at the last minute!

**Comment by ctm** [comment]
OK. If RubiABQ goes out for drinks tonight after our meeting, we won't look for beerjs.

I can't yet commit to tomorrow due to other stuff (not Yelptropolis). Additionally, I'm _still_ on the sidelines watching the cool kids play with ember while I'm preoccupied elsewhere (often in the mountains).

**Comment by samatjain** [comment]
I'm up for 7 pm tonight… anyone else? Waiting for confirmation from someone else…

**Comment by ianwcarlson** [comment]
I can't come.

**Comment by gbass84** [comment]
I'm in CA, maybe next time!

On May 28, 2015 3:28 PM, uıɐɾ ʞ ʇɐɯɐs <notifications@github.com> wrote:
I'm up for 7 pm tonight… anyone else? Waiting for confirmation from someone else…

---
