### ISSUE TITLE
Wednesday, June 24th Beers+JS, 7pm, Red Door

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#21]
Heya!

Already the end of the month! Swing by and we can pick up discussions on Ember, ES6, and whatever else people are doing!

**Comment by brianarn** [comment]
I'm out of town so it's not relevant to me, but that's Friday night?

**Comment by orbiteleven** [comment]
Ugh... I'm bad at dates.

**Comment by ianwcarlson** [comment]
In.

**Comment by brianarn** [comment]
I'm bummed I can't make it, because I have a gift for you, @orbiteleven, which is appropriate for the event.

**Comment by orbiteleven** [comment]
Argh! Deadline got moved up and we're behind. I'm not making this one. Hopefully y'all have fun!

**Comment by ianwcarlson** [comment]
Anyone else going?

Ian

**Comment by timmickey** [comment]
i just got here. pretty lonely
-Tim



—

**Comment by mark-casias** [comment]
Sorry I missed this month. Ended up having to wait late for my air conditioning to get fixed. 

Sweet, sweet air conditioning!

**Comment by ianwcarlson** [comment]
I think it would be useful to try to get a head count before it starts so
that people know if it's happening or not - which I realize is not
infallible.

**Comment by orbiteleven** [comment]
Terribly sorry to have missed this. I was planning on making it until about the time I sent that email when I realized I was going to need to burn midnight oil to make my EOD deadline today.

There's sort of a "chicken and egg" with these events where if everyone else is looking for someone else to go, we can end up having nobody attend. I think consistency with date and time are important, even if it's just 2 people. 

That said, if we can't get at least two people there month-to-month, perhaps we go to every-other-month?
