### ISSUE TITLE
Wednesday, July 29th, 7pm Red Door

### ISSUE THREAD

**Issue by ctm** [beerjs/abq#22]
I'm still not really doing anything appreciable with JavaScript, but I'll go.

**Comment by ianwcarlson** [comment]
I'll go.  I'm doing JS full time now.

**Comment by brianarn** [comment]
Assuming all goes to plan, my child will be ~6-7 hours old by this point, so I likely won't be making it. 2016 maybe! :D

**Comment by ctm** [comment]
Congratulations, Brian!

**Comment by ctm** [comment]
BTW, I don't know how to attach the Beer label to this issue. If anyone else knows how, please do (and let me know how to do it, if I have permission).

**Comment by brianarn** [comment]
In the upper right, there's a "Labels" area where you may or may not be able to add it. I've gone ahead and done so, since I have admin rights on this repo (because @orbiteleven is a nice guy), not sure how permissive labeling is.

**Comment by mark-casias** [comment]
@brianarn so you're saying we should take Lisa a beer at this point? She'll probably need one more than you.

**Comment by ianwcarlson** [comment]
I'm still planning on going, anybody else?

**Comment by ctm** [comment]
I'll be there. My hair is unkempt, below my ears and above my shoulders. I'll be wearing a rumpled buttoned gray short-sleeve shirt. No beard or glasses. Probably wearing shorts.

**Comment by samatjain** [comment]
I've a chest cold and thus won't be drinking, but will hang out.

**Comment by thoth** [comment]
Where are you all going to be sitting?





On Wed, Jul 29, 2015 at 3:05 PM -0700, "uıɐɾ ʞ ʇɐɯɐs" <notifications@github.com> wrote:












I've a chest cold and thus won't be drinking, but will hang out.

**Comment by samatjain** [comment]
We're outside
