### ISSUE TITLE
Wed, Aug 26 @ 7pm, Boese Brothers Brewing

### ISSUE THREAD

**Issue by samatjain** [beerjs/abq#23]
Getting a head start on this… did people want to hang out next week?

Any preference on Red Door vs anywhere else? I'm partial to La Cumbre and Chama myself…

**Comment by orbiteleven** [comment]
Thanks! Can't believe it's already EOM!

I'm going to guess this is supposed to be August, not July ;)

I'm fine with venturing. Chama, from my experience, can be difficult to get a variable-sized group sat. La Cumbre can get busy, too. I'm not opposed to either (or adding Canteen to the list), but Red Door has been pretty easy to "take over" if the group grows over a few folks.

What say we?

**Comment by samatjain** [comment]
Thanks for catching the wrong month! The day was right, at least.

At least since I've been part of the group, we've not had more than 5–6 people show up—and typically it's below that. Shouldn't be *too* difficult to get a table elsewhere?

**Comment by ctm** [comment]
I'm interested, but I'm running Leadville this weekend and my last couple of hundreds kicked me in the ass :-( so I don't know how much oomph I'll have after RubiABQ.

**Comment by mark-casias** [comment]
My vote is, and will probably be vetoed right away, Marble on the Westside. But that's because I am lazy and hate driving.

**Comment by ianwcarlson** [comment]
I can make it.  Would prefer a place where we don't have to yell at each other.

**Comment by lordtangent** [comment]
How about that new place downtown on Gold and 6th, Boese Brothers Brewery?

**Comment by mark-casias** [comment]
That's a good idea.. That's a beer I've never had.

**Comment by samatjain** [comment]
+1 for Boese Brothers

**Comment by orbiteleven** [comment]
Boese Brothers it is! See y'all Wednesday!

**Comment by gbass84** [comment]
great meeting! We talked about some cool stuff while I was there, I regret having to leave. Looking forward to the next one!
