### ISSUE TITLE
September 30th?

### ISSUE THREAD

**Issue by ctm** [beerjs/abq#24]
I'll be at [RubiABQ](http://www.meetup.com/Rubyists-in-Albuquerque/events/225379782/) from 6 until 8 at the latest, but am up for beerjs afterward.

**Comment by orbiteleven** [comment]
I'm down. What did we think about last month's venue, Boese Brothers?

**Comment by mark-casias** [comment]
I didn't get to go, so I have no opinion, however Rio Bravo Brewery is pretty good too.

**Comment by orbiteleven** [comment]
I'm open to trying Rio Bravo. Boese had decent beer, but it was insanely noisy with only a few folks there.

**Comment by mark-casias** [comment]
Wait.. September 23rd or 30th?

**Comment by ctm** [comment]
Oops.  Good point. It should be the 30th.

**Comment by mark-casias** [comment]
OK.. Tonight at Rio Bravo it is. Putting the announcement in nmdevs

**Comment by ctm** [comment]
Mark and I are at the picnic table in the back. It's quiet.

**Comment by gbass84** [comment]
I'm at the bar ATM, there's a blues band playing.

On Sep 30, 2015 12:57 PM, Mark Casias <notifications@github.com> wrote:
OK.. Tonight at Rio Bravo it is. Putting the announcement in nmdevs

---

**Comment by orbiteleven** [comment]
I suppose it's 5 o'clock somewhere ;)

**Comment by ctm** [comment]
Dude, with AIBF, you should have started drinking hours ago!

**Comment by mark-casias** [comment]
I question the quality of any Blues Band that tries to preform before 5pm.

**Comment by orbiteleven** [comment]
Maybe they never stopped from the night before?

**Comment by mark-casias** [comment]
In that case, they are probably really good. But only if they are on the same song.
