### ISSUE TITLE
September 30th, i.e. tonight?

### ISSUE THREAD

**Issue by ctm** [beerjs/abq#25]
Anyone going? I can make it, but as usual I'm still not doing much JS; I'm even behind in my beer drinking :anguished:.

There's a #javascript channel @ the [NM Tech Slack Group](http://nmdevs.org) and also an #announcements channel. I (or anyone else) can mention beerjs/abq if anyone is going to go.

BTW, I don't have the ability to tag this issue as beer, nor do I have the ability to close old issues. Someone who does, probably should. It may encourage more people to join.

**Comment by mark-casias** [comment]
Did we land on Rio Bravo?

**Comment by gbass84** [comment]
I'll be there, Rio Bravo was the last impression I got.

**Comment by brianarn** [comment]
I've changed #24 to have the label and correct date. Closing this issue in favor of tracking it there, since that had more info and did seem to list Rio Bravo as the consensus.
