### ISSUE TITLE
Oct 28 BeerJS, 7pm, Canteen Brewery

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#26]
Getting this on the calendar early. What did folks think of Rio Bravo?

**Comment by ctm** [comment]
Beer was nothing to write home about. Recently RubiABQ went to the [Nob Hill Bar and Grill](http://www.upscalejoint.com/bar) and they have some yummy Avery beers available on tap. It was sufficiently quiet that we had no trouble holding a conversation, although there were only four of us.

**Comment by mark-casias** [comment]
I liked the beer. The jazz band was nice and we sat out in the patio so it wasn't loud. I'm down with roving though.

**Comment by gbass84** [comment]
I wasn't particularly impressed with the beer either. Band was good and patio was quiet, but yeah... didn't get my two thumbs up.

**Comment by orbiteleven** [comment]
So... what are folks' thoughts? Nob Hill Bar and Grill is surely an option. Canteen Brewery (nee Il Vicino Canteen) is another spot with good beer, some food, and usually quiet enough.

**Comment by mark-casias** [comment]
I am not going to make it this month.

**Comment by ianwcarlson** [comment]
I've been wanting the try the Santa Fe brewing shipping container place but
I hear it's small.  I'm down for Il Vicino Canteen.

**Comment by samatjain** [comment]
The new Santa Fe Brewing Company Taproom is great, but it's still a bit hyper-popular right now and at 7 pm will be VERY crowded (I was there at 9 pm last night and there were no tables available even then).

**Comment by lordtangent** [comment]
I may or may not make it, so I'm down with wherever you guys choose.

**Comment by thoth** [comment]
Canteen is nice!

**Comment by orbiteleven** [comment]
Cool. Let's do Canteen Brewery tonight, 7pm.
