### ISSUE TITLE
December 30th 2015

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#29]
1. Is anyone interested since it's so close to NYE?
1. What did you think of Santa Fe Brewing?
1. Where would you like to go?

Discuss.

**Comment by orbiteleven** [comment]
1. Likely not here
2. I like it, but if we get larger it'd be hard to get a table.
3. ?

**Comment by ctm** [comment]
I'm going to pass on this one. I do enough drinking that time of year due to the [Foothills Fat Ass 50k](https://newmexicofa50k.wordpress.com/foothills-50k/). Everyone's welcome and it has shorter distances.

**Comment by mark-casias** [comment]
so this didn't happen..
