### ISSUE TITLE
Any interest for a meetup in February? 

### ISSUE THREAD

**Issue by thejones** [beerjs/abq#30]
I am in ABQ for two weeks 6th - 19th. Anybody have any interest in grabbing a few beers in that time frame?

**Comment by mark-casias** [comment]
Our scheduled drinkings are Jan 27th and Feb 24th. Albuquerque Drupal Users group will be meeting on the 11th if you would like to join. Of course coordinating an impromptu drink is always welcomed.

**Comment by thejones** [comment]
Sounds good. I am up for something and will reach out in Feb.

**Comment by orbiteleven** [comment]
Definitely reach out when you're here. I'd love to grab a beer.
