### ISSUE TITLE
First meetup of 2016: January 27th 

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#31]
Let the discussion of location begin! I would like to throw in http://www.lizardtailbrewing.com/home. It's in the NE corner, but has a lot of fine beers. Limited seating though.

**Comment by orbiteleven** [comment]
I'm open to it. @mark-casias perhaps we run recon in the next week or two?

**Comment by craig-davis** [comment]
Recon? Sign me up for that please.

**Comment by magicpinto** [comment]
That is across parking lot from my favorite Pho Restaurant in town.

**Comment by lordtangent** [comment]
I'm game to try Lizardtail

**Comment by ctm** [comment]
I'll be doing RubiABQ until 8pm, but will swing by Lizard Tail afterward.

**Comment by brianarn** [comment]
I should really try to make it out. Wednesdays wind up being bad for me lately, but who knows, maybe?

**Comment by ianwcarlson** [comment]
I won't be able to make it because my team is gearing up for a release.
Would love to talk about React and Angular though.

Ian

**Comment by lordtangent** [comment]
Can't make it on Wednesdays during the semester.

**Comment by orbiteleven** [comment]
Is anyone going to make it?

**Comment by mark-casias** [comment]
I'll be there.

**Comment by casualbrooks** [comment]
ill go after ruby.

**Comment by thoth** [comment]
Planning on it unless I get stuck in a work issue.

**Comment by brianarn** [comment]
if I make it, it won't be until like 8pm, but I'm trying to move my commitment tonight so that I can. :)

**Comment by GRALTOS** [comment]
It'll be my first time- what time do you guys meet? Need to bring my laptop or just my thirst??

**Comment by orbiteleven** [comment]
Thirst. I bring my laptop just in case, but it rarely comes out.

**Comment by mark-casias** [comment]
I’d say bring both..



Mark Casias
Sr Drupal Developer
T 678.580.1690 x212   F 770.360.5776
twitter <http://twitter.com/teampoop> • linkedin
<http://www2.mediacurrent.com/l/10072/2012-03-23/3qknq> • mediacurrent
<http://www2.mediacurrent.com/l/10072/2012-03-23/3qkpd>

**Comment by kimberlykeller** [comment]
I'll swing by, Lizard Tail is great. :D I haven't been to a beerjs before either, just let me know what time to come by.

**Comment by altintx** [comment]
Think I'll try for my first time, too

**Comment by orbiteleven** [comment]
I'll be getting there around 7pm. Look for the cowboy hat.

**Comment by ctm** [comment]
Kimberly, Brooks and myself were looking for others. My guess is the music was too loud and that you updated this issue, but GitHub dropped the ball.

**Comment by orbiteleven** [comment]
Shoot. I think we all expected someone else to update it. Or the update got lost in all of GH's issues yesterday. We'd moved over to Sinners & Saints across the parking lot.

**Comment by casualbrooks** [comment]
ohh we were a mere parking lot away! next time.

**Comment by atsjj** [comment]
Had a great time! Looking forward to the next one!
