### ISSUE TITLE
February 24th 2016

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#32]
Hey kids.. I won't be here, but there should be a meet up. Someplace new and exciting. How about the Draft Station (1720 Central Ave SW, Albuquerque, NM 87104)

**Comment by orbiteleven** [comment]
Don't tell me where to drink beer and talk nerdy...

...but The Draft Station is a good choice. I'm almost positive they won't have a 10-piece jazz band.

**Comment by mark-casias** [comment]
And if they do, there's a back room to move to..

**Comment by altintx** [comment]
It was fun last month. Think I'll be there. How's their food?

**Comment by magicpinto** [comment]
Okay. that band was awesome though.. Any group that rolls with 2 trombones is fine by me. 

Draft House sounds good to me.

**Comment by atsjj** [comment]
@altintx you're the only guy I know who asks about food when beer is the primary thing on the menu...

I'll see you all there!

**Comment by ianwcarlson** [comment]
I will be there as well.

**Comment by orbiteleven** [comment]
Called out to SF this week, so I can't make it. Have a good one!

**Comment by GRALTOS** [comment]
I'll be there too. 730?

**Comment by atsjj** [comment]
I plan on being there at 7:30 @GRALTOS

**Comment by ianwcarlson** [comment]
Anybody here?  I'm wearing a striped hoodie

Ian
