### ISSUE TITLE
March 30 Beers and Javascripts, Marble West Side, 7pm

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#33]
March 30 will be the last Wednesday of the month. Mark suggested the Marble Westside Tap, and since he's always trekking in from the west side, we can head out there this month. Who knows? Perhaps there are other JS devs out there.

I may be out of town that week, but I trust y'all will carry on without me!

**Comment by ctm** [comment]
I might be free on March 30th and wouldn't mind visiting Marble Westside. However, be aware that a band is listed for 6-9. I've never been to Westside, so I don't know if that would interfere with discussing JavaScript. I'm headed down to Las Cruces for a few days on April 1st, so if work is hectic that week I may not come out anyway.

**Comment by mark-casias** [comment]
Westside has just expanded and they have a large patio area where we should be able to get away from the band.

**Comment by mark-casias** [comment]
Well fucksticks.. I have a tennis match so I will probably miss..

**Comment by orbiteleven** [comment]
Ok, so who is going to make this? I'll be in San Francisco and @mark-casias will be playing tennis. I'd leave it up to the attendees to pick a spot since @mark-casias won't be there to request a westside location

**Comment by GRALTOS** [comment]
I can't make it this week.  Wife is out of town and we don't have a reliable baby sitter.  Next time.

**Comment by gbass84** [comment]
I have family in for a wedding, and while they're beer folks and one is 
a former Ruby Dev, I think I'll have to skip this one.

**Comment by altintx** [comment]
I'm up for it still.

**Comment by altintx** [comment]
Nobody else has chimed in and I don't want to go to the west side for an empty house, so guess I'll bail after all.

**Comment by mark-casias** [comment]
So time files... on to April
