### ISSUE TITLE
April 27th, 2016

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#34]
Figure I'll start this thread even though I am 90% sure I will be out of town. On that note: I won't force the issue of going to the west side again. On a second note, I am currently at the Corrales Bistro, and this is a good location.

**Comment by orbiteleven** [comment]
Excellent. I should be in town for this one. There are a number of new breweries I've not tried yet: Bow & Arrow, Rio Bravo... I'm pretty sure 2 more just opened while typing this.

**Comment by mark-casias** [comment]
FWIW: The Drupal group just met at Sidetrack on 2nd and Lead. Decent beer, but a great courtyard. Again, I won't be here so I don't get a vote.

**Comment by orbiteleven** [comment]
Oh, yeah. I really liked Sidetrack. They do cask-conditioned ales. This gets my vote.

**Comment by ctm** [comment]
Cask-conditioned ales gets my vote too. See you there.

**Comment by ianwcarlson** [comment]
I'm down.

**Comment by magicpinto** [comment]
Right next to Zendo.  Finally my "afternoon coffee" makes sense.  Sidetrack is perfect.

**Comment by orbiteleven** [comment]
Damn... so I'll be out of town on Wednesday, but y'all should definitely meet up. Damn work meetings getting in the way of beer.

**Comment by ianwcarlson** [comment]
Is anybody still going?

**Comment by magicpinto** [comment]
I am still working so won't make it.  =/

**Comment by ctm** [comment]
I am here. I got here late because RubiABQ ran late.
