### ISSUE TITLE
Job Openings

### ISSUE THREAD

**Issue by supersloth** [beerjs/abq#35]
My work is hiring new developers. The project involves Node/Scala/Cassandra/Redis/PostgreSQL. if you know those that would be great! if not i'm sure you can learn it as you go if you're a solid dev. email me your resume to joshua.rivera@gmail.com and we can exchange more details if you're interested.

**Comment by jden** [comment]
Remote ok?

**Comment by supersloth** [comment]
I wish. It's here in Abq.

**Comment by ianwcarlson** [comment]
There's a local frontend developer opportunity at [my company](https://www.risksense.com/careers/#.V1H4PJMrKV4).  We're using cool tech (React, Redux, D3, Git, Node dev tools), but don't expect applicants to have experience with those specifically, just exposure to a modern MVC framework and solid developer skillset.  Please direct salary questions to the website.   If you have questions about the position I can post more info here or I think you'll be able to reference me when you email the company.  If you can't tell, I'm not super jazzed about leaving my email here.

**Comment by orbiteleven** [comment]
Is this cool to close?

**Comment by supersloth** [comment]
yes
