### ISSUE TITLE
May 25th (Marble Downtown)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#36]
May is upon us and instead of picking a place and then not being around to enjoy it, I'm gonna let y'all discuss it instead. I will throw Marble West in the ring just cause I hate driving.

**Comment by erictheise** [comment]
I'll be visiting from San Francisco between the 19th and 29th and look forward to meeting up with you folks.

**Comment by erictheise** [comment]
I'll add that I'm staying in Martineztown and, while I can probably get a ride out to & back from Marble West, it'd be an easy walk to Tractor on 4th, Marble on Marble, or Rio Bravo.

**Comment by mark-casias** [comment]
Well I am nothing if not accommodating to our visitors. Let's say we meet at the Marble on Marble. 6:30, this coming Wednesday. Any objections?

**Comment by orbiteleven** [comment]
Marble mothership works for me, but I'm slightly concerned it'll be a zoo?

**Comment by orbiteleven** [comment]
Heya! Are we still looking at Marble Downtown? I'm still concerned that we won't be able to capture enough space there.

How was Sidetrack last month?

**Comment by mark-casias** [comment]
I think it would be neat to try out the new roof patio. I say we stick with it.

**Comment by orbiteleven** [comment]
Is it open? Is it packed?

**Comment by mark-casias** [comment]
not there yet. Will tell you when we get there.

**Comment by mark-casias** [comment]
I am here. The upstairs is not open but I have a big table all to myself.

**Comment by craig-davis** [comment]
On my way.

**Comment by mark-casias** [comment]
Check that. I am in the back corner on the couch with Damon.

**Comment by orbiteleven** [comment]
These are actually couches, but we have space

**Comment by orbiteleven** [comment]
Awesome time folks! Let's do it again next month!

**Comment by erictheise** [comment]
It was great to meet you all last night. Lot of fun hearing the conversations veer from tech to personal history to mountain biking and paddleboarding. I'll hope to join you again sometime down the road–@mark-casias, if I can give you enough notice I'd be happy to propose a webgeeks talk–and @orbiteleven & others, feel free to ping me next time you travel to the Bay Area.
