### ISSUE TITLE
Opportunity

### ISSUE THREAD

**Issue by kwinckler** [beerjs/abq#37]
Hi,

I am new to this group and want to know if it is appropriate to post job opportunities here.

I originally started a software company in ABQ at 2nd and Central...and it was later sold to a public company.  I have started a new company focusing on tenant payments to landlords and we are a little over 1/2 the way to our initial V0 release...there are three of us currently.  I am looking for additional help from someone experienced in JavaServer Faces.  It would be great to grab a beer or coffee with anyone interested.

Thanks,
Kris Winckler
kris@schedulemyrent.com
480-5669

**Comment by orbiteleven** [comment]
Sorry we didn't respond in a timely fashion. Did you find someone? Is this cool to close?

**Comment by mark-casias** [comment]
Ping 2 on this issue. Closing in February if no response.
