### ISSUE TITLE
June 29, 7pm, Location TBD

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#38]

**Comment by ianwcarlson** [comment]
Anybody want to drink beer tomorrow?

**Comment by mark-casias** [comment]
Huge fan of drinking beer. Wanna go to Duel and then maybe the downtown Red Door soft opening?

**Comment by casualbrooks** [comment]
Sound like good plans! And a little js on top.

**Comment by orbiteleven** [comment]
I'm in!

**Comment by craig-davis** [comment]
Duel? What time?

**Comment by mark-casias** [comment]
7pm. Duel is on Central between 6th and 7th (closer to 6th)

**Comment by orbiteleven** [comment]
@mark-casias isn't the Simms Taproom soft opening at 4pm?

**Comment by mark-casias** [comment]
Yeah. I was thinking of going there first, then to Duel. I am under the impression that it'll be a cluster at R2D2, so meet at the meeting time at Duel and then you get to make the executive decision to go back to R2D2 (yes. I be referring to that location as R2D2 from now on.

**Comment by ctm** [comment]
See y'all @ 7 @ Duel.

**Comment by kimberlykeller** [comment]
I'll be at Duel at 7 as well! I'm excited to be able to make a beer js this
month.
