### ISSUE TITLE
July 27, 7pm, Bow and Arrow?

### ISSUE THREAD

**Issue by orbiteleven** [beerjs/abq#39]
The end of the month is upon us. Let's continue our "downtown-ish breweries" kick and head to the gorgeous Bow and Arrow: http://www.yelp.com/biz/bow-and-arrow-brewing-albuquerque

**Comment by mark-casias** [comment]
Sounds good to me

**Comment by ianwcarlson** [comment]
I should be there

**Comment by ianwcarlson** [comment]
I'll be there tonight.

**Comment by ctm** [comment]
I'll be there.

**Comment by pixelsaurus** [comment]
Count me in!

**Comment by craig-davis** [comment]
I'm in. What time?

**Comment by ianwcarlson** [comment]
@craig-davis Meetup stardate: -306429.53096539166  (today at 7pm)
