### ISSUE TITLE
August 31st, 7pm, Marble NE Heights

### ISSUE THREAD

**Issue by ctm** [beerjs/abq#40]
Suggestions?

**Comment by orbiteleven** [comment]
Beer and talking nerdy?

Marble opened their new Northeast Heights location. Might be worth checking out, though it might be insanely far for everyone. I'm open to it, though.

**Comment by mark-casias** [comment]
I am down for Marble East.

**Comment by magicpinto** [comment]
Marble east would be awesome!  Plus the slice parlor is there if anyone is
hungry for a slice.

**Comment by ctm** [comment]
I'll be @ Marble East, although I won't be drinking, 😡. Due to  [this](http://runningjohn.blogspot.com/2016/08/2016-mountain-madness-fat-dog-120-race.html) and [that](http://ultrasignup.com/event_waitlist.aspx?did=35421).

**Comment by pixelsaurus** [comment]
What time again?

**Comment by orbiteleven** [comment]
7pm
