### ISSUE TITLE
December 28th, 2016. Palmer Brewery and Cider House

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#45]
Trying to get a pulse on people who may be in town for this last week of 2016. Anyone?

**Comment by brianarn** [comment]
I'll be in town and would love to make it out to an event. Would have made last month if illness hadn't infested my family.

**Comment by aindaco1** [comment]
I’m down.

[https://htmlsigs.s3.amazonaws.com/logos/files/000/340/161/landscape/logo.png]<http://hermesdevelopment.com/>   Alonso Indacochea / President
alonso@hermesdevelopment.com<mailto:alonso@hermesdevelopment.com>
Hermes Development
hermesdevelopment.com<http://hermesdevelopment.com/>

On Dec 5, 2016, 8:36 AM -0700, Brian Arnold Sinclair <notifications@github.com>, wrote:

I'll be in town and would love to make it out to an event. Would have made last month if illness hadn't infested my family.

**Comment by kimberlykeller** [comment]
I'm in town

**Comment by ctm** [comment]
I should be available.

**Comment by xrnm** [comment]
Count us in!

**Comment by mark-casias** [comment]
Sounds like there is enough interest. Then I propose we try the new Palmer Brewery and Cider House. 2924 Girard Blvd NE, 87107 (Girard and Candelaria)

**Comment by elizabeth8890** [comment]
If I'm here I'll make it!  Likely me +1 (nontechnical person) if so.

Thanks so much for your help last time!  My data mining project will be
over in less than 24 hours!
