### ISSUE TITLE
January 25th 7pm at Dialogue Brewing

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#46]

**Comment by mark-casias** [comment]
Taking location suggestions.

**Comment by xrnm** [comment]
1. Rio Bravo
2. Red Door

**Comment by ctm** [comment]
Rio Bravo appears to have a nicer selection of beer, but Wednesday night is a free movie night (7pm-9om). I don't know if that will interfere with conversation.

I haven't been drinking lately, so the beer selection doesn't mean too much to me this month (and probably not in February, either).

It's awfully quiet here. Who all is thinking about attending?

**Comment by kimberlykeller** [comment]
I'll be there, Rio Bravo is nice, but I agree it might be loud. We haven't
been to Dialogue yet, which is usually pretty laid back and the beer is
decent. That would be my recommendation.

**Comment by jhellman** [comment]
I'm planning on attending this time, albeit possibly a bit late.

**Comment by mark-casias** [comment]
So lets do Dialogue. And by "Lets" I mean y'all cause I won't be able to make it.

**Comment by mark-casias** [comment]
1501 1st St NW, Albuquerque, NM 87102

**Comment by michaeldeitcher** [comment]
I'll be there a little bit later as well.

**Comment by ctm** [comment]
I'll be there. I'm going to the [RubiABQ](https://www.meetup.com/Rubyists-in-Albuquerque/events/237060960/) meeting first. In theory that runs from 6-8, but if looks like we'll have a light turnout, so it may end earlier than normal.

**Comment by ayodernm** [comment]
I know its too late for this months meeting but Quarter Celtic has a good selection of beers and some tasty treats as well (Lomas/San Mateo)

**Comment by mark-casias** [comment]
I'll open the issue for Feb on that location. Great suggestion.

**Comment by elizabeth8890** [comment]
Hi!  If I can I'll make it to Ruby and maybe beer.js but am under a
deadline now for this weekend!

**Comment by mark-casias** [comment]
err.. January is definitely over...
