### ISSUE TITLE
February 22nd @ Kelly's Brewpub 7pm

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#47]
7:00
3222 Central Ave SE, Albuquerque, NM 87106

Stay for Leeside

**Comment by elizabeth8890** [comment]
Good Morning,

I know there's no meeting this week but I was writing to see if anyone
wanted to get together this workweek to talk about the Neo4j javascript
driver with me?  I don't have to use it but want to anyways, to compare to
what I'm doing in R and Python.  I'll buy you lunch, dinner, beer,
whatever.  Please email me directly at elizabeth8890@gmail.com if you're up
for it!

Thank you
--Elizabeth

**Comment by orbiteleven** [comment]
Any chance I can divert this to Kelly's?

1. Kelly's has been purchased by Santa Fe Dining (of Chama & Marble fame) so the beer/wine selection isn't crap
1. It's a huge space
1. My band, Leeside is playing (It's a big space so you'll be able to sit far enough away to talk)
1. It's my last BeerJS before leaving for Denmark

**Comment by elizabeth8890** [comment]
I'll be there!  Love the band!!!!

**Comment by mark-casias** [comment]
That sounds good. Except for the whole "last BeerJS" bullshit. I'll update the issue and we can do Quarter Celtic next month.

**Comment by elizabeth8890** [comment]
Damon maybe there could be CDs this time with you on it if possible?
Looking forward!!!

**Comment by elizabeth8890** [comment]
Hi!

As always, looking forward to the band tomorrow!

Is there going to be anyone attending tomorrow who knows Spark?
This actually is a Javascript related question.  :) If so I'd love to
discuss.

Thank you
--Elizabeth

**Comment by elizabeth8890** [comment]
Apache Spark, that is!  :)

On Tue, Feb 21, 2017 at 10:35 AM, Elizabeth Kallman <elizabeth8890@gmail.com

**Comment by ctm** [comment]
I'm looking forward to seeing everyone tonight. I'll be doing [RubiABQ](https://www.meetup.com/Rubyists-in-Albuquerque/events/237773786/), first though.

**Comment by elizabeth8890** [comment]
I'll likely miss you, unless I bring my computer and at some point go off
and sit in the corner or something to start working...ha maybe!  Deadlines!
