### ISSUE TITLE
puts "hello, nerds!"

### ISSUE THREAD

**Issue by zacts** [beerjs/abq#48]
Hello,

It's Zak from the meetup. I was just saying hello here to introduce myself officially(?) (As I guess I should formally join the group via the GitHub). :-D. (My apologies if this is the wrong place to post a join to the group).

About me? I'm a Linux nerd, and I like all kinds of stuff. I like Linux. I like Music. I like languages, but I'm still learning. I'm beginning to teach myself the ancient Attic Greek alphabet, and soon vocabulary and grammar to learn Plato. I like the Jazz piano, especially the late Bill Evans trios. I also like Miles Davis So What and all that. I'm also interested in this Lojban http://lojban.org, but I'm just getting started with it. The idea of using it as an Intermediate Representation language is kind of a cool idea to me. It's a spoken human language based on formal mathematical logic which can be parsed into an AST very easily, or something like that. Machine Learning is too specific for what I think I want to study in college. I'm going for Philosophy + <Something Else> + a Languages minor for a more general foundation.

My setup: I use URxvt + vim + tmux + i3wm on Linux (Ubuntu for now, but I like Slackware too).
I like the command line quite a lot. I'm also interested in learning about making electronic music a la Deadmau5 maybe eventually via something like SuperCollider.

I know nothing about network security. Well, my depths of knowledge are OpenSSH and http://mosh.mit.edu/. I know of LibreSSl, but don't know how to do anything other than basic SSH basically. I'm not interested in network security. I'm more interested in languages and interactions between components.

I'm interested in Languages + Programming Languages + Source to Source Translation + Ruby (et everything associated with Ruby) + lispy stuff. I'm a newbie sort of, but not really, but I do have gaps in knowledge sometimes depending on what was interesting to me at any given moment.

I'm hoping to tackle this Structure and Interpretation of Computer Programs by MIT Press.

I <3 rhythmic wordplay lingos too. Like tinkering with languages. I like Noam Chomsky, including his political writings that I'm starting with.

I'm just starting to learn about PEG parsing over regex.

I also prefer the term nerd > geek apparently because 'nerd' was apparently coined by Dr. Seuss's book If I Ran the Zoo. Geek has an odd etymology in comparison.

I like music: https://soundcloud.com/zachary-storer/tuning-to-the-stars-draft-2 <-- I'm trying to compose a piece for piano + strings. It's pretty relaxing, called Tuning to the Stars, and it tunes the piano in perfect 5ths just like the violins tune. The above clip only is fragments of what I have in my mind. I just need to save up for a cello to really get into it.

My GitHub is lame for now. https;//github.com/zacts. My Blog is even more lame: http://zacts.github.io/. <-- I will probably switch to Jekyll for it, but I wanted to force myself to learn some CSS for my blog (but it just became a giant ToDo that never ended up happening), to not rely on any frameworks, but I'll just do jekyll + theme.

Ok,

Eventually, once I learn Ruby and all that maybe I'll work on some entry level projects towards a job.

-

Zak

**Comment by zacts** [comment]
If anyone might want to mentor me that would be awesome too... Like for like weekly meetups for pair coding or something. (just to throw the idea out there).

**Comment by mark-casias** [comment]
Closing issue. Hope to see you at more meetups!
