### ISSUE TITLE
March 29th Meetup @ Celtic Quarter (1100 San Mateo Blvd NE #50)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#49]
Hey there. I know I said Celtic Quarter, but I need someplace with reliable internets because I'll be doing a fantasy baseball draft at the same time. So, either we go there after someone verifies the wifi situation or I am taking suggestions. Thanks.

**Comment by ctm** [comment]
Any ideas? I'm hoping that the choice will be someplace quiet enough for me to hear what others are saying. Especially if anyone attending has any thoughts on [Cycle.js](https://cycle.js.org), [TypeScript](http://www.typescriptlang.org) and/or [RxJS](https://github.com/Reactive-Extensions/RxJS).

**Comment by mark-casias** [comment]
Let's go ahead and call it Celtic Quarter for this month. I am going to bow out this month but y'all should totally talk RxJS.

**Comment by ctm** [comment]
Is anyone else planning on going?

I can be there at the standard 7pm or earlier since there's no RubiABQ this week.

I realize that we typically have people show up who don't write comments here, but it would be helpful to me if at least one person confirms that he/she is attending.

**Comment by kimberlykeller** [comment]
I'll be there!

**Comment by ctm** [comment]
Nice beer. Loud. I'm at a tiny table, but can see the door. When more come we can go outside and perhaps hear each other.
