### ISSUE TITLE
May 31st

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#51]
Taking requests for a location, but am thinking Red Door on Candelaria. 6:30pm. All in favor?

**Comment by ianwcarlson** [comment]
That sounds good to me.

**Comment by ctm** [comment]
I'll be there. I mentioned it to the RubiABQ group last night. A few others said they'd go.

**Comment by xrnm** [comment]
Count a few of us in!

**Comment by altintx** [comment]
In for 2.

**Comment by mark-casias** [comment]
See y'all tonight at Red Door: https://goo.gl/maps/JsDAcVGeCbz

**Comment by brianarn** [comment]
GREAT SUCCESS

MUCH MEETING
