### ISSUE TITLE
June 28th: Steel Bender BrewYard

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#52]
8305 2nd St NW

**Comment by xrnm** [comment]
I'll be out of town for this one.

**Comment by ianwcarlson** [comment]
Are we doing 6:30 again?

**Comment by ctm** [comment]
I'll be coming after RubiABQ, which may mean shortly after 8. OTOH, we have a light turnout and might break early.

**Comment by mark-casias** [comment]
Yes. 6:30. 

 ![](http://i.imgur.com/FfqWpF1.jpg)
