### ISSUE TITLE
Consider switching to meetup.com?

### ISSUE THREAD

**Issue by sgrif** [beerjs/abq#54]
I get that it costs money but as someone moving back to Albuquerque, it is ridiculous how hard it is to find meetup groups. The value of the web site is not for organization, it's that *it's where people look*. If I didn't happen to know the right people to ask, I never would have found out about this meetup group.

**Comment by mark-casias** [comment]
First, let me say, Welcome back! Looking forward to drinking many a beer with you!

We have had this discussion before and it was decided we will continue to use this repository as our main point of contact for this group. This group is a subset of the original BeerJs. You'll notice this is one repo of many who are using it throughout the globe. It was the original intention of the organizers and we want to honor that. Now that you are here, follow the repo and you'll get notifications about the group. Meetup tends to bring in people who just want to troll groups to sell their wares or get free support. I have experienced this first hand and want to avoid that. Additionally, we won't try to suggest any other groups that your friends friends mom started. We are happy you have found us and hope you and your friend will join us at Starr Brothers at the end of the month.
