### ISSUE TITLE
August 30th at Duel

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#55]
August is a 5 Wednesday month so the gathering has been set. See y'all there

**Comment by ctm** [comment]
Tell me when to be there and I will.

**Comment by ctm** [comment]
It'll be at 6:30pm.

**Comment by ChromaQ** [comment]
I'll be there! We should hit up Nexus sometime, I heard that they have awesome hot wings.
-Sarah Swanson

**Comment by ctm** [comment]
Should we set up an issue for September 27th at Nexus?

**Comment by mark-casias** [comment]
done.. we can quit living in the past!
