### ISSUE TITLE
September 27th @ Nexus (I-25)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#56]
Our September meetup is set! 7ish at Duel Brewing (606 Central Ave SW). Mark your calendars

**Comment by ctm** [comment]
Shouldn't this be Nexus, @mark-casias? We went to Duel in your absence. We're sneaky like that.

**Comment by mark-casias** [comment]
updated.. I should learn to not copy and paste.

**Comment by altintx** [comment]
We're sitting on left when you walk in

**Comment by tkah** [comment]
Are any of you all still here?

**Comment by srfinkel** [comment]
Is there a meet up for Oct or at y'all taking a break for Halloween?
