### ISSUE TITLE
Wed October 25, 2017: Tractor 4-Hills (118 Tulane Dr SE)

### ISSUE THREAD

**Issue by altintx** [beerjs/abq#57]
October meetup.

**Comment by altintx** [comment]
Think we were talking about Tractor on Tramway?

**Comment by ctm** [comment]
I'll be out of town, visiting my father and running the [Javelina Jundred.](https://vimeo.com/139420728) Have fun.

**Comment by mark-casias** [comment]
I have a previous engagement tomorrow (Marble West Side anniversary) so I can't make it. I was going to suggest moving it to there but I have a feeling it's going to be very crowded.

**Comment by brianarn** [comment]
kiddo has a school event during this time :( which is a bummer since this is currently so close to my home

**Comment by brianarn** [comment]
which is to say, I could probably make it but it'd be significantly later than like 6:30 or 7pm, wouldn't be until kids were in bed, which is like ... 9? that feels super late tho.

**Comment by srfinkel** [comment]
Since people are having some conflicts for tomorrow, can we do Thu instead? Same location?

**Comment by sgrif** [comment]
Why are these announced so late? It's very difficult for people with kids to make arrangements to attend a meetup on such short notice.

**Comment by sgrif** [comment]
Why is this meetup announced on such short notice? It's very difficult for folks with kids or busy schedules to attend. Typically most meetup groups announce dates at least one month in advance.

**Comment by erictheise** [comment]
@sgrif, about a year ago I knew I'd be visiting Albuquerque for Thanksgiving so I opened #43 weeks ahead of when the group would likely meet up. Just open an issue if you need discussion and resolution earlier.

**Comment by sgrif** [comment]
It should not require an attendee opening an issue to find out the date of a meetup more than a day in advance. I have a family and other arrangements, literally every month I would need to do that if that's what it takes.

**Comment by mark-casias** [comment]
@sgrif this is an open source community. Plan on the last Wednesday of the month, because that's always when we meet.

**Comment by sgrif** [comment]
@mark-casias I cannot find that documented anywhere. Should it be in the README?
