### ISSUE TITLE
November 29th, 2017: 6:30p Nexus Brewery (4730 Pan American Fwy NE)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#58]
Since it's a holiday month, let's start the conversation for the November Meet-Up. I am thinking we haven't been to Nexus in a while.

**Comment by srfinkel** [comment]
Wed Nov 29 should work for me. Nexus works too.

**Comment by ctm** [comment]
I'm fine with Nexus. Are we talking about the one at 4730 Pan American Fwy NE? Since there are five Wednesdays in November, there's no conflict with RubiABQ or Thanksgiving. Yay!

**Comment by mark-casias** [comment]
Definitely the one off of I-25.. The one off of Coors doesn't have food. Updating description.

**Comment by ctm** [comment]
I'm here a half hour early. I've snagged us a couple of tables that are just to the left as you come in.

**Comment by srfinkel** [comment]
It's been a hell of a week. Perhaps I will see you all in the new year :)

**Comment by mark-casias** [comment]
or even in december! Hope to see you soon.
