### ISSUE TITLE
December 27th @ Red Door Heights (3517 Wyoming Blvd, NE)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#60]
Yes it's a holiday week and a good portion of us may or not be able to attend, but hey.. if you can, it'll be spiffy. Plus the new Red Door location!

**Comment by srfinkel** [comment]
might work for me!

**Comment by ctm** [comment]
I'm not going tonight. I've had a nasty lingering cold that is still giving me trouble this morning.

So instead of saying it in person:
> Happy New Year, y'all.

**Comment by srfinkel** [comment]
how many people are attending tonight? I have a sick partner at home so I'm debating if I should attend or go home and make him some green chili chicken posole.

**Comment by mark-casias** [comment]
My suggestion:
- Make Posole
- Give him a bowl
- Bring rest to meeting.

**Comment by srfinkel** [comment]
LOL @mark-casias. Doesn't seem like too many people are attending tonight so I think meeting up next year will be better. 
 
Be well everyone!

**Comment by mark-casias** [comment]
I am here sitting at the bar. If someone else shows up, we can get a table.
