### ISSUE TITLE
February 28th: Bow and Arrow (608 McKnight Ave NW [6th and I-40]) 6:30pm

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#62]
No one could remember if we were at Bow and Arrow, so we are going there.

**Comment by brianarn** [comment]
As someone who doesn't know the locations of things (and doesn't necessarily trust map searches) can we get an address and start time tacked into things?

**Comment by mark-casias** [comment]
valid point. Issue updated.

**Comment by mark-casias** [comment]
Food is hurting here. Be warned.
