### ISSUE TITLE
March 28th. Marble Downtown (111 Marble NW) 6:30

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#63]
We had a vote. Marble Downtown won.

**Comment by ChromaQ** [comment]
I believe I'll be there! -Sarah Swanson

**Comment by brianarn** [comment]
I'm planning on it right now, though who knows

**Comment by ctm** [comment]
I have RubiABQ first (I'm doing an introductory presentation on the [scientist gem](https://github.com/github/scientist)). I may stop by after. I'd like to see people, but my sleep schedule has been perturbed lately and I have no idea what I'll feel like then.

**Comment by brianarn** [comment]
I think I’m the only person here maybe? Didn’t see others I recognized.

**Comment by ctm** [comment]
Justin and I are on our way. We are leaving Ideas & Coffee "now".
