### ISSUE TITLE
May 30th, 6:30pm Ponderosa (1761 Bellamah Ave NW)

### ISSUE THREAD

**Issue by ctm** [beerjs/abq#65]
Any plans?

**Comment by mark-casias** [comment]
I thought we said Ponderosa, but the lack of open issues says otherwise.  I have to miss this month.

**Comment by ctm** [comment]
OK. I've updated the issue text, but I don't have privs to add the beer label. Does it make sense to give me such privs?

**Comment by mark-casias** [comment]
@ctm you will have to ask the main repo owners to add you to the team. I do not have that privilege. At least I don't think I do. I did add the label though.

**Comment by altintx** [comment]
We’re on the patio 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
