### ISSUE TITLE
June 27th Steelbender (8305 2nd St NW) @ 6:30p

### ISSUE THREAD

**Issue by thejones** [beerjs/abq#66]
Anybody interested in meeting 1 week from today at Steelbender? I noticed there is nothing for June so delete this if there are proper channels to create an event.

**Comment by mark-casias** [comment]
We talked about it at ABQWebGeeks but I never made the issue, so you win! Steelbender it is.

**Comment by thejones** [comment]
Is 6:30 the usual time @mark-casias?

**Comment by altintx** [comment]
Usually we're the last wed of month (June 27) is this truly intended to be the Thursday before (June 21)?

**Comment by mark-casias** [comment]
Oh I didn't even grok the date.. yes.. 6/27 at 6:30.. updating title.

**Comment by thejones** [comment]
Did not realize there was a method to the madness ;) The 27 is good for me!

**Comment by altintx** [comment]
I'm not sure that we'll make it tonight :(

**Comment by mark-casias** [comment]
Boo hiss!

**Comment by brianarn** [comment]
I'll likely make it but closer to 7 than 6:30 I bet

**Comment by thejones** [comment]
I am about five minutes out.

**Comment by mark-casias** [comment]
At the patio bar

**Comment by mark-casias** [comment]
Now we are at a table on the patio behind the bar

**Comment by brianarn** [comment]
it happened yayyyyy
