### ISSUE TITLE
July 25th, 2018 at ABQ Brew Pub (6601 Uptown Blvd NE) at 6:30p

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#67]
Where shall we meet in July?

**Comment by altintx** [comment]
Hey it's tomorrow, are there any new places? Seems like we try to avoid repeats but I'm coming up dry.

**Comment by ianwcarlson** [comment]
I'm not sure, but I'm going

**Comment by ctm** [comment]
If we choose a repeat, I vote for Duel, just because I'd like to try their Goya.

**Comment by mark-casias** [comment]
Have we been to the ABQ Brew Pub in Uptown?

**Comment by brianarn** [comment]
Sounds like nothing concrete, so let's try this?

Using Reactions to this comment, cast your vote:

- 👍 for Duel
- 🎉 for ABQ Brew Pub

or make a suggestion but since we're day-of and there's already two ideas, maybe let's go with one of the above. I'm using both reactions because I don't have a preference and it also makes it easier for others to vote.

Let's call the vote over at like 2pm?

**Comment by ClecknerT** [comment]
👍

**Comment by brianarn** [comment]
ABQ Brew Pub has a significantly larger vote, looks like it wins

Someone who knows what/where that is precisely should put that in here

Hope to see you all somewhere tonight

**Comment by ClecknerT** [comment]
Time?

**Comment by mark-casias** [comment]
Updated the issue title to reflect the win. See y'all there

July 25th, 2018 at ABQ Brew Pub (6601 Uptown Blvd NE) at 6:30p

**Comment by timmickey** [comment]
Where are you all sitting?

**Comment by altintx** [comment]
On the left as you walk in

**Comment by mark-casias** [comment]
Be there soon

**Comment by brianarn** [comment]
That was some good times, y'all

**Comment by altintx** [comment]
I totally forgot. I was going to ask you, given the reaction emoji’s you chose, if you could say... the hoor-yays have it.

**Comment by ctm** [comment]
I wasn't able to make it, because Jamii and I got involved tracking down a JavaScript problem. If it were straight JavaScript, I might have headed over and asked you all, but it's really an issue with Rails 5.2's use of the webpacker gem and how webpack is configured. FWIW, we made a bunch of progress, but I did miss getting together with everyone. Looking forward to next month.

**Comment by ianwcarlson** [comment]
@altintx @brianarn This is the [HTTP proxy](https://portswigger.net/burp/communitydownload) I was talking about at the last meetup. It's called Burp Suite Community Edition. I don't think you can save anything, but it doesn't do annoying things.

**Comment by xrnm** [comment]
@ctm

I've done some work with webpacker and rails 5.1+. Happy to take a peek at
it if that would be helpful.

{~Justin Edwards~}
Founder
Iterative Consulting, LLC
Data analytics, data visualization, web applications
http://iterative.consulting
(505) 750-4837
Justin@Iterative.Consulting

**Comment by ctm** [comment]
Thanks for the offer, @xrnm !

The problem turned out (eventually!) to be fairly simple. Webpacker by default doesn't run Babel over stuff in the `node_modeules` subdirectory, but Foundation 6 uses constructs that don't work on ie11.

This solved it:
```
--- a/config/webpack/environment.js
+++ b/config/webpack/environment.js
@@ -1,6 +1,9 @@
 const { environment } = require('@rails/webpacker')
 const jQueryConfig = require('./jQuery')
 
+const babelLoader = environment.loaders.get('babel')
+babelLoader.exclude = /node_modules\/(?!(foundation-sites)\/).*/
+
 environment.config.merge(jQueryConfig)
 
 module.exports = environment
```

**Comment by xrnm** [comment]
@ctm

Fascinating. Haven't played with Foundation at all, but I have had to use
Polyfills to solve similar issues.

Glad y'all figured it out.

{~Justin Edwards~}
Founder
Iterative Consulting, LLC
Data analytics, data visualization, web applications
http://iterative.consulting
(505) 750-4837
Justin@Iterative.Consulting
