### ISSUE TITLE
August 29th, 2018: Duel (606 Central Ave SW) 6:30p

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#69]

**Comment by ClecknerT** [comment]
Any react-native developers in the group?

**Comment by ChromaQ** [comment]
I'll probably be there! - Sarah

**Comment by brianarn** [comment]
I should be there, hopefully, I want to rave about the 505 React group and encourage others to go to that too when it happens again

**Comment by mark-casias** [comment]
I should be there, but I have a gig on Thursday and they may want to call a practice..

Also.. I have a gig at Rio Bravo on Thursday  8/30 for those of you who like more beer and good music. #shamelessplug

**Comment by ctm** [comment]
I'll be @ Duel tonight. As much as I'd like to, I won't be @ Rio Bravo tomorrow. Must ... shoot pool ... and drink. Thursdays are like that.
