### ISSUE TITLE
September 26th. La Cumbre West (6:30pm)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#70]
Newly opened and solid beer.  5600 Coors NW Suite C1

**Comment by brianarn** [comment]
hey hey, it's today

I can't recall what time we usually do things though, I want to make sure I give myself ample time for the journey

**Comment by ctm** [comment]
6:30. I expect to be there, although this is my last week at Decisiv and even smallish emergencies will take precedence.

**Comment by mark-casias** [comment]
Updated time to 6:30..

**Comment by ctm** [comment]
Am here, at bar

**Comment by mark-casias** [comment]
We are now at a table by the door

**Comment by mark-casias** [comment]
good times everyone..
