### ISSUE TITLE
November 28th: Broken Trail Brewing 6:30p - end

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#72]
6902 Menaul Blvd NE (Menaul & Louisiana area)

Fork and Fig is next door for some delicious dinner and Flying Phillies..

**Comment by ctm** [comment]
Not that I know of. Let's give it a go.

**Comment by ctm** [comment]
Are you sure we don't want to go to [6902 Menaul NE](https://www.google.com/maps/place/6902+Menaul+Blvd+NE,+Albuquerque,+NM+87110/@35.1086916,-106.5681387,19z/data=!4m5!3m4!1s0x87220acdb202fdf3:0x6ddc01a563143a24!8m2!3d35.1086916!4d-106.5675915)?

Messing around with Google Maps and reading their [website](https://brokentrailspirits.com) makes me think the Stanford location may just be where they make it, not where we can drink it.

**Comment by altintx** [comment]
I don't know... I could have walked to the Stanford location.

No idea if they have a tap room though, or if we'd just be huddled in the
parking lot.
