### ISSUE TITLE
December 26th: Steel Bender (8305 2nd St.)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#73]
I’ll add the address later

**Comment by ctm** [comment]
Assuming I have the right [web-site](https://steelbenderbrewyard.com/contact-us/), their address is: [8305 2nd St.](https://www.google.com/maps/place/Steel+Bender+Brewyard/@35.1752115,-106.6275007,17z)

**Comment by mark-casias** [comment]
You are correct sir! 2nd and just south of Paseo.

**Comment by ctm** [comment]
Looks like I won't make it. I just got called on a SAR mission. Incident Base is the top of the crest. This is going to be tricky.

**Comment by altintx** [comment]
I just arrived but don't see anybody. Know Cliff is out but is anyone else
coming? There is live music.

**Comment by brianarn** [comment]
Had a last-minute out of town friend who could only get together tonight :(
