### ISSUE TITLE
Feb 27th 2019: Toltec Brewing 6:30pm

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#75]
10250 Cottonwood Park NW, Albuquerque, NM 87114

**Comment by ClecknerT** [comment]
Looking forward to this. Any Electron Devs in this group?

**Comment by Splode** [comment]
I use Electron at work and in some personal projects. I've been a long-term lurker of this group, but haven't yet been to a meetup. I'll join y'all this week.

**Comment by ctm** [comment]
Not an Electron dev, nor do I do much JavaScript, but I've been writing a bunch of Rust lately and am curious about compiling to WASM. If anyone shows up with that experience, I'll have some questions. Otherwise, I'll drink beer and listen.

**Comment by brianarn** [comment]
I edited to add the time because I swear I can never remember it and then I dig it up from old events

**Comment by ctm** [comment]
The upside is arriving on time. The downside is not arriving a half hour early. I'm at the bar...

**Comment by brianarn** [comment]
Running late but I’m on my way.
