### ISSUE TITLE
March 27th 6:30p - Differential Brewing (500 Yale Blvd SE, Albuquerque, NM 87106)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#76]
hey all.. March is blowing in like a lion, so let's go have beer. I know we discussed a location but for the life of me I can't remember what it was. I picked last month, but there is a new brewery in the UNM area called Differential Brewing (500 Yale Blvd SE, Albuquerque, NM 87106). Any other ideas?

**Comment by Splode** [comment]
Haven't been there before, but that sounds good to me 👍🏼

**Comment by ctm** [comment]
I just put Differential on my calendar, although I have a family event that will probably preclude my attendance this month.
