### ISSUE TITLE
April 24th, 2019 @ 6:30.. Rio Bravo Brewing (1912 2nd St NW)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#77]
Open for suggestions on a location.

**Comment by mark-casias** [comment]
After a discussion in Slack, the location is Rio Bravo! 1912 2nd St, Albuquerque, NM 87102

**Comment by brianarn** [comment]
I’m running late but should be there

**Comment by mark-casias** [comment]
Did anyone discuss next months location?
