### ISSUE TITLE
May 29th, 2019. 6:30p - Bombs Away Brewing (9801 Acoma Rd SE Albuquerque, NM 87123)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#79]
Issue for the May 2019 get together. Any suggestions for the location are welcomed.

**Comment by ctm** [comment]
I tried querying on #javascript in the ABQ Web Geeks Slack workspace, but have yet to get a reply. I'm in town and up for a beer tomorrow evening, but I don't have any suggestions.

**Comment by mark-casias** [comment]
Well you started a great conversation. I am updating the location to Bombs Away Brewing. I've never been and it satisfies Sara's request for non-food-truck-food..

**Comment by Splode** [comment]
Here’s their site, by the way:
[Bombs Away Beer Company site](https://bombsawaybeer.com/)

**Comment by mark-casias** [comment]
On my way but very late
