### ISSUE TITLE
July 31st, 2019 - 7PM - Thirsty Eye Brewing (206 Broadway Blvd SE, Albuquerque, NM 87102)

### ISSUE THREAD

**Issue by xrnm** [beerjs/abq#81]
Wanted to get an issue made for this month. What locations sound good to y'all?

**Comment by mark-casias** [comment]
A new brewery is in town and it our moral duty to try it out. Thirsty Eye is at Broadway just south of Central. Thanks for opening the issue, I literally was thinking about it this morning.

**Comment by xrnm** [comment]
Awesome. We were super late to the game last month and that led to a small turn out.

I'm excited to check this place out!

**Comment by ctm** [comment]
I'm out of town. Someone might want to post this to the two Slack teams. Have fun all!
