### ISSUE TITLE
August 28th 7PM @ La Reforma Brewery (8900 San Mateo NE)

### ISSUE THREAD

**Issue by xrnm** [beerjs/abq#82]

**Comment by altintx** [comment]
La Reforma Brewery?  https://lareformabrewery.com/

**Comment by mark-casias** [comment]
Sold!

8900 San Mateo Boulevard Northeast, Albuquerque, New Mexico 87113, United States

**Comment by brianarn** [comment]
if I didn't have this night, and only this night, to see good friends of mine who are moving back to the UK for awhile, I would totally make this night

Hopefully I'll see y'all in September - I should be able to make that one

**Comment by brianarn** [comment]
I dunno if I somehow jinxed things but plans are changing and I may be able to make it after all, might see y'all there :)

**Comment by altintx** [comment]
We got a table. Walk in turn right turn left. Maybe you can see us from the door. Maybe.
