### ISSUE TITLE
2019 October 30 6:30pm @ Canteen Taproom 417 Tramway Blvd NE, Albuquerque, NM 87123

### ISSUE THREAD

**Issue by altintx** [beerjs/abq#83]
Who's up for it this month?

**Comment by xrnm** [comment]
In London, so I won't be there.

**Comment by mark-casias** [comment]
I'll  be in Amsterdam, but the 31st I'll be in Denmark doing a beerJS with Damon..

**Comment by brianarn** [comment]
I think I might actually be able to make this one

**Comment by ctm** [comment]
I'll be in town, but I'm still without a vehicle and it'll be my first day back in town after leaving Thursday the 24th. 

It's been a while and I miss everyone (not that _everyone_ will be there), but I'll have to make my decision sometime on the 29th or 30th.

**Comment by altintx** [comment]
Sounds like everybody is on the east side. There's a Tractor on Central & Tramway. Feelings?

**Comment by brianarn** [comment]
That's literally five minutes from my house - I'm still not 100% sure I'm gonna be able to make it so my take shouldn't be factored in heavily, but I like the location :D 

There's also a Canteen Taproom on Tramway just north of the freeway, and a friend of mine has been raving about Turquoise Trailer Brewery ( https://goo.gl/maps/3YKjzquED1dd59mD6 ) although I don't think they're brewing their own beer just yet, still getting going.

**Comment by altintx** [comment]
🚀 For Canteen Taproom
👀 For Turquoise Trail
❤️ For Tractor

**Comment by dubaaron** [comment]
Sorry to chime in so late, but have been wanting to come again sometime, and looks like I may make it tonight, if anyone else is around.  Canteen sounds cool to me; I don't drink beer so availability of food / non-alc drinks will always be a larger factor for me, and looks like they have food, so 👍 : ) 

EDIT: oops, don't know why I always get it in my head BeerJS happens on Tuesdays ... which is clearly wrong, contradicting both the title of this issue and the readme ... less likely I can make it tomorrow :/  but maybe.

**Comment by altintx** [comment]
The rocketships have it: Let's do Canteen on Tramway @ 630 Wednesday

**Comment by ctm** [comment]
I'll be there. In (a sideways) honor of BeerJS, I've just started a spike to see if I can use [yew](https://github.com/yewstack/yew) to hack a text-mode web interface onto [mb2](https://github.com/ctm/mb2-doc). Whee!

**Comment by brianarn** [comment]
Me earlier this week: Halloween is on Thursday so I should be able to make today!
Me today: Shit I have so much I have to do for Halloween ugh

Maybe I'll see y'all next month :/

**Comment by ctm** [comment]
I'm not going to make it after all. I'm fading fast. Bummer.

**Comment by dubaaron** [comment]
Doesn't look like I'm making it either, sorry to say; hope someone else will be there if you're going, @altintx

**Comment by altintx** [comment]
We are on patio. They have heaters and the World Series is on.

**Comment by altintx** [comment]
We are gonna head out catch y’all next month
