### ISSUE TITLE
November 27th, Ex Novo in Coralles. 7pm (address in comment)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#84]
4895 Corrales Rd, Corrales, NM 87048

**Comment by ctm** [comment]
I'm going.

**Comment by altintx** [comment]
I'm in

**Comment by ctm** [comment]
For what it's worth, I added an amazingly crappy (currently text-only) [web-interface](http://devctm.com:8080) to [my poker server](https://github.com/ctm/mb2-doc) and deployed it last night. No longer do people need an IRC client to play-test. I'll bring my laptop and demo it.

Right now it requires ridiculous amounts of typing ([you can't even abbreviate commands)](https://github.com/ctm/mb2-doc/issues/35) so a keyboard is needed to play, but by Wednesday I should be well into my experimentation with adding buttons for at least the most widely needed commands and _perhaps_ it will be playable on phones by then.
