### ISSUE TITLE
December 2019 BeerJS discussion

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#85]
Hey all.. Since the last Wednesday of the month falls on Christmas, I propose we move the meet up to Thursday December 26th. Location is to be determined, but I figure I should start the discussion now.

Discuss..

**Comment by ctm** [comment]
Drink beer and discuss JavaScript on a Thursday!? I drink beer and shoot pool on Thursdays, so ... how about we have BeerJS/ABQ on Thursday, December 26th (Boxing Day), but at Anodyne (which is where I am pretty much every Thursday evening; in fact, I just got back from there now).?

That (assuming we do it at Anodyne) works for me.
