### ISSUE TITLE
January 29, 2020: Boes Brothers Brewing NE Heights (7849 Tramway Blvd, Suite C)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#86]
Happy New Years! Let's all fail at Sober January properly on the last Wednesday of the month. While we have been at Boes Bros before (alliteration aside) we have not been to the new NE Heights location on Tramway at Paseo del Norte. 6:30ish - whenever.. See you there.

**Comment by ctm** [comment]
I should be there. I might even have some WebGL questions, but I probably won't :-)

**Comment by ctm** [comment]
They are closed, due to a beer malfunction. I’m going to get gas. Any ideas?

**Comment by mark-casias** [comment]
Starr Brothers?

**Comment by ctm** [comment]
Sure.  See you there.
