### ISSUE TITLE
April 29th 2020: Pandemic Brewing (Virtual)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#88]
Hey let's get a zoom beer thing going on.

**Comment by ctm** [comment]
I will be there. I assume this is 6:30 MDT.

What I'll be drinking will depend on the answer to the question:

> Does anyone have $25,000 so I can buy a beer?

FWIW, I'm serious. For more details, contact me off list.

In related news, I've been running [nightly test tournaments](https://github.com/ctm/mb2-doc#play-testing) on mb2 at 6pm Mountain. Most of the people who show up are from [BARGE](https://www.barge.org/), but starting yesterday I started widening the net. Currently the site is a complete ghost town except during those tournaments, but that will change.

**Comment by ctm** [comment]
Deleted my previous email, in case it put a damper on this discussion. If so, I apologize.

What's the plan?

**Comment by brianarn** [comment]
I'm not sure, but I have a paid zoom account so I could create a meeting for it, if desired, that won't shut down in 40 mins

**Comment by brianarn** [comment]
May as well make one now, since I can:

Brian Sinclair is inviting you to a scheduled Zoom meeting.

Topic: BeerJS Pandemic Edition, April 2020
Time: Apr 29, 2020 06:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://us02web.zoom.us/j/87359389592?pwd=eG9QRllLVEFZNnF0ZVNqdURnRW9ydz09

Meeting ID: 873 5938 9592
Password: 8675309
One tap mobile
+13462487799,,87359389592#,,1#,8675309# US (Houston)
+16699009128,,87359389592#,,1#,8675309# US (San Jose)

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 669 900 9128 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 312 626 6799 US (Chicago)
        +1 646 558 8656 US (New York)
        +1 301 715 8592 US (Germantown)
Meeting ID: 873 5938 9592
Password: 8675309
Find your local number: https://us02web.zoom.us/u/keq12I2AWp

**Comment by brianarn** [comment]
I made the meeting start at 6pm because I was too lazy to change it to 30 and also it means people can get there at 6:25 and it won't be like "THIS MEETING HAS NOT STARTED"

Also I allowed join before host in the event that somehow I don't make it and/or am late

**Comment by ctm** [comment]
Thank you! Very nice.

**Comment by ctm** [comment]
Oops ... I think that's 6pm Pacific.

**Comment by mark-casias** [comment]
Well shoot.. I totally spaced this and have band practice for the first time in a pandemic ago.. thanks Brian for getting it set up.

**Comment by brianarn** [comment]
hm apparently if I do this it'll kick my kid off, lol, one moment, trying to sort

**Comment by brianarn** [comment]
okay it's up

**Comment by ctm** [comment]
Thank you, @brianarn for setting it up. I apologize for monopolizing the conversation, dwelling on Rust and calling JavaScript a shitty language. In all three, I was attempting humor, but perhaps that's incompatible with drinking tequila out of a beer stein (or perhaps I just need more practice). If only I weren't so lazy and could have had that beer I had been (and still am) looking forward to ...

Thank you, @mark-casias for scheduling it, even if you couldn't make it.
