### ISSUE TITLE
June 24th 2020 @ 5:30 Tin Can Alley (6110 Alameda Blvd NE)

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#89]
Hey all, just getting feelers out on how we want to proceed for this months meet up. Do we want to try to get together or keep it virtual?

**Comment by ctm** [comment]
In person!

**Comment by altintx** [comment]
Think it's been six months since I made it out... Combination of availability and pandemic. I'm desperate to get out to an event.

Would have a definite preference for outdoor though (fresh air). Hopefully it's not too hot.

**Comment by mark-casias** [comment]
If in person, I think we should checkout the new Tin Can Alley (Santa Fe Brewing). The only issue is they close at 8p (I think all places are still closing early) so we may want to start at 5:30 or 6.

https://santafebrewing.com/taproom/tin-can-alley/

**Comment by ctm** [comment]
works for me

**Comment by mark-casias** [comment]
So just got word that Tin Can Alley doesn't serve out of SFBC (only to-go)... so we may want a second option.

**Comment by altintx** [comment]
It may be worth waiting another week to figure out a place. At the rate things are changing it could be different in another 2 weeks anyway.

**Comment by ctm** [comment]
Since SFBC @ TCA is open now, should we make it official? If so, what time.

Yes, I know it's a week away, but for once in my life I'd like to do something that involves planning ahead.

**Comment by altintx** [comment]
Hey, if they're open now; that was the point of waiting right? Let's make it so.

**Comment by mark-casias** [comment]
Made so... Set the time for 5:30 since it closes so early. See y'all there and I am pretty excited that we actually organized this a week ahead instead of an hour..

**Comment by mark-casias** [comment]
PS: I feel we should set up a zoom room for those who want to participate but are still uncomfortable with being in public.. (because of the pandemic, not just in general). Not sure if it'll work well or even if there's wifi there..

**Comment by kipdec** [comment]
Have any of you made it here yet? Sitting outside of Santa Fe brewing in a NASA shirt

**Comment by altintx** [comment]
I just... touched down?

**Comment by mark-casias** [comment]
I am on my way

**Comment by ctm** [comment]
I apologize, but I bailed. I got there and they said a 30 to 40 minute wait.
