### ISSUE TITLE
September 30th 2020: Red Door Brewing Downtown (509 Central Ave SW) 6:00pm

### ISSUE THREAD

**Issue by mark-casias** [beerjs/abq#91]
Red Door has been doing work to their patio so let's try to go to there.

**Comment by ctm** [comment]
I'll be there. I'll also set up a Zoom if nobody else does. I'm still a leach though, so in theory we can only go 40 minutes on my free plan.

**Comment by altintx** [comment]
I'll probably be closer to 630

**Comment by ctm** [comment]
I'll try to get there a little before 6, so I can have the Zoom running by 6 (@mark-casias is going to set me up on a paid account so we don't have to worry about it dropping off).

**Comment by mark-casias** [comment]
Zoom info is in #javascript on the ABQWebgeeks slack.
