### ISSUE TITLE
25 November 2020

### ISSUE THREAD

**Issue by altintx** [beerjs/abq#92]
It's the day before Thanksgiving. Let's hope that it's warm.

**Comment by altintx** [comment]
According to today's announcement, in person is out for November.

**Comment by ctm** [comment]
Saddenz.

**Comment by mark-casias** [comment]
SriptsGiving Zoom?

**Comment by ctm** [comment]
@mark-casias Yes, please.

**Comment by mark-casias** [comment]
Zoom information is in #javascript in ABQWebgeeks slack (and Tech Community of NM).. Starting at 6pm..
